### ISSUE TITLE
T.V Series 

### ISSUE THREAD

**Issue by bornprincess** [romreviewer/TorrentVilla#5]
T.V series Epi is not working pls fix that problem as soon as possible

![Screenshot_2020-04-18-18-58-34-625_torrentvilla romreviwer com](https://user-images.githubusercontent.com/63912339/79639064-ca7d8780-81a6-11ea-9eff-648a7395c093.jpg)

**Comment by romreviewer** [comment]
Thank You for notifying this issue is fixed now please restart TorrentVilla app you will be able to find Series.
