### ISSUE TITLE
Details section is missing in new update

### ISSUE THREAD

**Issue by CreAvenger** [romreviewer/TorrentVilla#8]
Hey Torrentvilla team....
Hello from India
I am Harshal Shahu and a very old user of torrentvilla app

Your app has made many changes in the interface of the app. Some are very good but some are not.

Your previous versions had an option to view the details of torrent we're downloading..

And it's very imp for user like me to see if the file I'm downloading has which resolution, it's 8 bit or 10 bit, audio quality is 320 kbps or 120 kbps, audio's source (if it's from Bluray or dvd), some screenshots (this one's very imp)

I hope you got my point.

We want this feature team torrentvilla.

Please provide 

Thank you.

**Comment by romreviewer** [comment]
Hello,
Currently this option is only available in 1337x server you will be able to view details in that server only just filter that server we will add this feature to more servers soon.
